### ISSUE TITLE
IndexOutOfRangeException when playing a map with mines and bridges near map borders

### ISSUE THREAD

**Issue by Frount** [OpenRA/OpenRA#10039]
Bridges、mines place on the map outside，will couse the game to crash out.
![1](https://cloud.githubusercontent.com/assets/15920974/11291967/25490ac0-8f82-11e5-95a4-65b965afa21d.jpg)
If i set mine like this,when game start it just crash out……

**Comment by abcdefg30** [comment]
Can you post the exception.log, please?
That looks similar to #9528.

**Comment by Frount** [comment]
Red Alert Mod at Version playtest-20151114
on map cf938ace1a342370253190b67a1dcf0f7036703e (a by Your name here).
Operating System: Windows (Microsoft Windows NT 5.1.2600 Service Pack 3)
Runtime Version: .NET CLR 4.0.30319.1022
Exception of type `System.IndexOutOfRangeException`: 索引超出了数组界限。
   at OpenRA.CellLayer`1.get_Item(CPos cell)
  at OpenRA.Mods.Common.Traits.ResourceLayer.GetResource(CPos cell)
   at OpenRA.Mods.Common.Traits.SeedsResource.<Seed>m__0(CPos p)
   at System.Linq.Enumerable.<SkipWhileIterator>d__52`1.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__b1`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at OpenRA.Mods.Common.Traits.SeedsResource.Seed(Actor self)
   at OpenRA.Mods.Common.Traits.SeedsResource.Tick(Actor self)
   at OpenRA.World.<Tick>m__3(TraitPair`1 x)
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by abcdefg30** [comment]
Yes, this was fixed in #9528 and thus the crash should not appear in the next version.
Thanks for the report anyway!

**Comment by pchote** [comment]
@abcdefg30: actually the crash log tells us that this still happens in the latest playtest...

**Comment by reaperrr** [comment]
SeedsResource doesn't seem to check whether the cell it wants to seed on exists, while the bridge crash is probably caused by a bridge hut being placed outside the map.

**Comment by Mailaender** [comment]
Can't reproduce the problem with bridges placed near map borders. Please post a map where this happens and re-open. The problem with mines has been addressed in https://github.com/OpenRA/OpenRA/issues/10062.
