### ISSUE TITLE
Units continue to target enemies under fog

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#10294]
Sometimes a unit will track an enemy under fog of war but will not move to attack them. You can follow the enemy unit by the red attack line.

On bleed. 
##

**Comment by atlimit8** [comment]
Do you mean without GPS?
#9953 added targeting under fog if GPS is used.

**Comment by abcdefg30** [comment]
It's actually quite noticeable on Fort Lonestar when the arty fires on your units. They don't move/attack, but show a red targetline, iirc. This has also something to do with the `Defend` stance then.

**Comment by anjew175** [comment]
I have seen this as well for TD wtih inf tracking recon bikes however when I reselected the unit they lost the red attack line

**Comment by pchote** [comment]
This has been fixed for a long time.

**Comment by GraionDilach** [comment]
Umm, this still happens with turrets, although we have #12856 for that.

**Comment by pchote** [comment]
Indeed.  This issue was specifically about the target lines.

**Comment by GraionDilach** [comment]
Ah, nvm then.
