### ISSUE TITLE
Make more RA debris traversable / buildable on 

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#15840]
RA debris are great esthetical elements for map making. 

However, in a game context, they can be very obnoxious, especially when trying to deploy a MCV. 

Many of the exisiting debris are very subtle to the eye, and it would be more believable to ba able to build on. For example : 
![2018-11-20 19_27_35-openra](https://user-images.githubusercontent.com/20139967/48794644-dd163780-ecfa-11e8-9994-3973937a58c4.png)

(disregard the top left rock of course)

I'll try to do a list later on, of what tiles should be made traversable.

**Comment by reaperrr** [comment]
Pretty sure at least the bottom two were buildable on in the original anyway. In any case, it would make sense going by their visuals either way.

**Comment by MustaphaTR** [comment]
> Pretty sure at least the bottom two were buildable on in the original anyway. In any case, it would make sense going by their visuals either way.

Top-left cell of bottom left debris isn't buildable.

**Comment by netnazgul** [comment]
Also there is a problem with some road tiles having building blockers.

And then, there is an issue with desert tileset not having debris as "rough" (so they look much the same like in temperate/snow, but are passable and buildable)

**Comment by KOYK** [comment]
Note that we only have one debris tile that can block building placement , and also allow units to walk on it. this is good since you can block base pushing in some maps but allow at the same time units to walk.
Actually I think we need also more of those.

**Comment by netnazgul** [comment]
@KOYK yes, it's the tile255 - second in the third row. But would be nice to have several others also be traversible, like these
![image](https://user-images.githubusercontent.com/1614714/50370858-846ae080-05bf-11e9-9294-f6246c796a04.png)

AFAIR at the moment they are neither buildable (like all the debris) nor traversible

**Comment by KOYK** [comment]
@netnazgul thats what i said :p

**Comment by Dasha-98** [comment]
This makes the map "[Tiger Core](https://resource.openra.net/maps/13502/)" (from Westwood Studios) unplayable. 
The player with the spawn point at the top is completely blocked in his spawn area.

Australia map from Westwood has also large parts not traversable too.

I also think that each debris tile cell should have these parameters : 
- buildable
- traversable by ground unit 
- traversable by water unit 
- traversable by ground fire
- traversable by water fire (sub's fire)
- traversable by "dropped" fire (arty, missile sub, ...) --> like concrete walls have

**Comment by Dasha-98** [comment]
I verified the file [snow.yaml](https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/tilesets/snow.yaml) and to make more debris traversable (like tile 223).

If we look at 223 for instance, all its cells are marked as rocks where in the original game, they behave as rough.

Rock = not traversable, not buildable
Rough = traversable, not buidable

The fix is fairly easy, and does not require any code change, only configuration changes in the terrain yaml files, but the change shall be agreed before going ahead with it as I don't know if there is a rationale to deviate from the original game for the tiles behaviour.

**Comment by Dasha-98** [comment]
As discussed on the Discord, I've started to make an inventory between the OpenRA tiles cells and the ones in the original game.

I've first focus on the **road** tiles.
Here's the output of my inventory for snow and temperate.

For each tile, I've listed the cells that have a different behaviour.

	182
		1:
			OpenRA : Rock
			Red Alert : Rough
	185
		7:
			OpenRA : Rock
			Red Alert : Rough
		10:
			OpenRA : Rock
			Red Alert : Rough
	186
		4:
			OpenRA : Rock
			Red Alert : Rough
	188
		8:
			OpenRA : Rock
			Red Alert : Rough
	190
		8:
			OpenRA : Rock
			Red Alert : Rough
	193
		0:
			OpenRA : Rock
			Red Alert : Rough
		5:
			OpenRA : Rough
			Red Alert : Clear
	200
		2:
			OpenRA : Rough
			Red Alert : Clear
	213
		0:
			OpenRA : Rock
			Red Alert : Rough

Desert are not present in the original game. And in OpenRA, desert roads have only cells with categories "road" or "clear". So they are not concerned by this issue.

**Comment by Dasha-98** [comment]
And here're the discrepencies for the debris tiles : 



temperat and snow :

103
	0:
		OpenRA: Rock
		Red Alert: Rough

104
	0:
		OpenRA: Rock
		Red Alert: Rough

109
	0:
		OpenRA: Rock
		Red Alert: Rough
	1:
		OpenRA: Rock
		Red Alert: Rough
	2:
		OpenRA: Rock
		Red Alert: Rough
	3:
		OpenRA: Rock
		Red Alert: Rough
	4:
		OpenRA: Rock
		Red Alert: Clear
	5:
		OpenRA: Rock
		Red Alert: Clear

110
	0:
		OpenRA: Rock
		Red Alert: Rough
	1:
		OpenRA: Rock
		Red Alert: Rough

216, 218, 219, 220, 221, 222
	0:
		OpenRA: Rock
		Red Alert: Rough

223, 224, 225
	0:
		OpenRA: Rock
		Red Alert: Rough
	1:
		OpenRA: Rock
		Red Alert: Rough

226
	0:
		OpenRA: Rock
		Red Alert: Clear
	1:
		OpenRA: Rock
		Red Alert: Clear


tempat :

580 --> 588 are not in Red Alert and are defined as rough which makes sense imho.

desert :

3
	0:
		OpenRA: Rock
		Red Alert: Rough
	1:
		OpenRA: Rock
		Red Alert: Rough

39
	0:
		OpenRA: Clear
		Red Alert: Rough
	1:
		OpenRA: Clear
		Red Alert: Rough
	2:
		OpenRA: Clear
		Red Alert: Rough
	3:
		OpenRA: Clear
		Red Alert: Rough

40, 44 --> not present in Red Alert but all cells shall be updated from clear to rough to be consistent with 39

41
	0:
		OpenRA: Rough
		Red Alert: Clear
	1:
		OpenRA: Rough
		Red Alert: Clear
	2:
		OpenRA: Rough
		Red Alert: Clear
	3:
		OpenRA: Rough
		Red Alert: Clear
	4:
		OpenRA: Rough
		Red Alert: Clear
	5:
		OpenRA: Rough
		Red Alert: Clear
	6:
		OpenRA: Rough
		Red Alert: Clear		

42
	0:
		OpenRA: Rough
		Red Alert: Clear
	1:
		OpenRA: Rough
		Red Alert: Clear

43 --> not present in Red Alert but all cells shall be updated from rock to rough to be consistent with temperat and snow

**Comment by ThomasChr** [comment]
Imho we should fix that. But there may be maps out there which rely on the old behaviour. @PunkPun recommended that we should give map creators the ability to decide for themselves which tiles should be traversable/buildable. So maybe we can have some kind of presets (old OpenRA preset / original Red Alert preset) and map creators choose which one to use. Also they can override it tile by tile - but I'm not sure such fine grained behaviour is necessary.

**Comment by ThomasChr** [comment]
Just to note here: You could also kill trees in the original Red Alert. So maybe thats worth considering here too.

**Comment by Dasha-98** [comment]
Hi, this issue is still present.

After some time, I wanted to play a LAN game on original map Tiger Core and my friend was stuck in its base. I then remembered this ticket.

Is there a consensus to fix, if so, I can do the required changes in the Yaml's.

**Comment by Dasha-98** [comment]
As confirmed by tux on Discord, there is no appetite to change the tiles behaviour to make them behave in the orignal game. 
Rationale : it can break currently used maps.
This ticket can be closed I guess.

**Comment by Dasha-98** [comment]
Here're the files tiles file updated so that they match with the RA behaviour.
They reflect my analysis here above.
[tilesets_original_ra.zip](https://github.com/user-attachments/files/17416084/tilesets_original_ra.zip)
