### ISSUE TITLE
The SpreadDamage Bug is back!

### ISSUE THREAD

**Issue by RedlerSchnyder** [OpenRA/OpenRA#16357]
I made a overpowered unit for myself with a ridiculous damage and blast radius with a spread of 7c0 and on many plays I did, this happened.
```
OpenRA engine version release-20190314
Tiberian Dawn mod version release-20190314
on map 1ba72e36e25ac3a2bcbd9814d78e6f6594bba8b5 (Fortresses II by Insert Name & Kane).
Date: 2019-03-26 23:07:58Z
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Attempted to calculate the square root of a negative integer: -2120092899
   at OpenRA.Exts.ISqrt(Int32 number, ISqrtRoundMode round)
   at OpenRA.Mods.Common.HitShapes.PolygonShape.DistanceFromEdge(WVec v)
   at OpenRA.Mods.Common.HitShapes.PolygonShape.DistanceFromEdge(WPos pos, Actor actor)
   at OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.<DoImpact>c__AnonStorey1.<>m__0(HitShape s)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at OpenRA.Exts.CompareBy[T,U](IEnumerable`1 ts, Func`2 selector, Int32 modifier, Boolean throws)
   at OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.DoImpact(WPos pos, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.Mods.Common.Warheads.DamageWarhead.DoImpact(Target target, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.GameRules.WeaponInfo.Impact(Target target, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.Mods.Common.Traits.Explodes.OpenRA.Mods.Common.Traits.INotifyKilled.Killed(Actor self, AttackInfo e)
   at OpenRA.Mods.Common.Traits.Health.InflictDamage(Actor self, Actor attacker, Damage damage, Boolean ignoreModifiers)
   at OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.DoImpact(WPos pos, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.Mods.Common.Warheads.DamageWarhead.DoImpact(Target target, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.GameRules.WeaponInfo.Impact(Target target, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.Mods.Common.Projectiles.Bullet.Explode(World world)
   at OpenRA.Mods.Common.Projectiles.Bullet.Tick(World world)
   at OpenRA.World.<Tick>m__5(IEffect e)
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)
```

**Comment by reaperrr** [comment]
@pchote What's your opinion on just limiting max total spread to `int.MaxValue`?

**Comment by RedlerSchnyder** [comment]
How about limiting it to at least 64 cells?

**Comment by pchote** [comment]
The real bug here is isn't the spread, but the poor handling of integer overflows in the HitShape code or something it uses.  I'd much prefer that we could isolate where the problem is, because it can probably be fixed by making one or two lines use `long`s.

**Comment by RedlerSchnyder** [comment]
Although this bug is still prevalent, I found an alternative thanks to the introduction of the cluster weapon logic in the recent update. Making the clusters spread in circles is complicated but it works fine! I don't have to worry about the crashing from that integer overflow, so thanks for the help and the update.
