### ISSUE TITLE
Bleed: Restarting the game repeatedly randomly freezes

### ISSUE THREAD

**Issue by Orb370** [OpenRA/OpenRA#18691]
[Restart_Bug_Video.zip](https://github.com/OpenRA/OpenRA/files/5351828/Restart_Bug_Video.zip)

[server.log](https://github.com/OpenRA/OpenRA/files/5351832/server.log)

[Pchote Troubleshoot Conversation.txt](https://github.com/OpenRA/OpenRA/files/5351842/Pchote.Troubleshoot.Conversation.txt)

![001663](https://user-images.githubusercontent.com/42915475/95525245-9b9bdd80-09a1-11eb-8707-e1ee1c330c21.png)

This is on bleed. Doesn't appear to occur on release. Game will eventually freeze if you continually restart a mission. Occurs randomly (can be the first restart, or the 5th). Occurs in both RA/TD mods.

I first encountered this bug around July 24th-ish.

**Comment by pchote** [comment]
> Unknown server command: startgame

I suspect some kind of race condition gets the server confused, which leaves the server struck in the lobby state and the player (which doesn't have a lobby UI) stuck on the last tick of the fade out of the old world.

**Comment by abcdefg30** [comment]
Also see #18250.

**Comment by Orb370** [comment]
I tested bleed, it appears to have been fixed. Wasn't able to reproduce.

Probably #18700 fixed it. Closing.

**Comment by pchote** [comment]
We've seen several reports of this happening on recent bleed / devtest builds, so this is still an issue.

**Comment by pchote** [comment]
I was just able to reproduce this on current bleed, so it is definitely still an issue. Same `Unknown server command: startgame` as previously.

**Comment by pchote** [comment]
The startgame order is being rejected because `client == null` at https://github.com/OpenRA/OpenRA/blob/b1560ae69ceece55d9c5b40d5a1ed71d4c408c86/OpenRA.Mods.Common/ServerTraits/LobbyCommands.cs#L97-L98



The actual problem appears to be a race condition on `LobbyInfo.Clients`. When changing

https://github.com/OpenRA/OpenRA/blob/b1560ae69ceece55d9c5b40d5a1ed71d4c408c86/OpenRA.Game/Server/Server.cs#L864-L865

to

```csharp
var client = GetClient(conn);
Console.WriteLine("Command from player index {0}", conn.PlayerIndex);
foreach (var c in LobbyInfo.Clients)
	Console.WriteLine("{0}: {1}", c.Index, c.Name);

var handledBy = serverTraits.WithInterface<IInterpretCommand>()
	.FirstOrDefault(t => t.InterpretCommand(this, conn, client, o.TargetString));
```

I see
```
Command from player index 1
1: Paul
Command from player index 1
1: Paul
2: Cabal
```

on a successful restart, and
```
Command from player index 0
0: Paul
Command from player index 0
1: Paul
2: Cabal
```

on an unsuccesful restart.

**Comment by pchote** [comment]
The initial conditions for triggering this bug are actually set when entering the skirmish lobby. Most of the time you will be assigned PlayerIndex: 0, but sometimes you are assigned PlayerIndex: 1. The restart option works by overriding the lobby info with the state from the previous game, which breaks if your player index changes between the two.

**Comment by pchote** [comment]
Regression from #18026. We are now joining local servers using both IPv4 and IPv6 loopback connections, and then dropping one connection. We are usually dropping the slower connection, but not always.
