### ISSUE TITLE
SDL_GL_DeleteContext, X11_SafetyNetErrHandler endless loop

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#19027]
I ran into a SDL bug.

Possibly related to `Sdl2GraphicsContext` being called from a different thread. Possibly a SDL library bug.

Version: bleed
OS: Linux Ubuntu
SDL library used: /home/x/source/cs/OpenRA/bin/SDL2.so

Not reproducable. Happened after i ran into graphics/render performance issues. Believe i've seen similar behavior in the past.

Steps:
- git checkout of bleed
- make
- launch, start OpenRA, using ./bin/SDL.so
- See ShellMap and menu
- Quit OpenRA using Quit button
- OpenRA Window no longer renders/refreshes.
- Observer mono does not exit, bash prompt does not return
- kill -QUIT to see mono stack trace, see below
- Seems only the ThreadedGraphicsThread is still running
- Using Linux perf top to see what it is doing.
- 99.3% time spent in SDL2.SDL.SDL_GL_DeleteContext
- Using gdb to see the thread is stuck in X11_SafetyNetErrHandler symbols available
- Browsing the source code (version not checked) http://www-personal.umich.edu/~bazald/l/api/_s_d_l__x11video_8c_source.html
- Noticing that `safety_net_triggered == SDL_TRUE`
- Breakpoint shows X11_SafetyNetErrHandler is called continesouly, not recursively
- Noticing that `orig_x11_errhandler == X11_SafetyNetErrHandler` which results in the callback loop

----
mono thread dump:
`
Full thread dump:                                                               
                                                                                
"ThreadedGraphicsContext RenderThread"  at <unknown> <0xffffffff>               
  at (wrapper managed-to-native) SDL2.SDL.SDL_GL_DeleteContext (intptr) [0x00012] in <9e175edc1f654e30934cb6367bbba576#24B6BFF2-4F08-E2DD-AA7C-9596708ADC74>:0
  at OpenRA.Platforms.Default.Sdl2GraphicsContext.Dispose () [0x00022] in /home/x/source/cs/OpenRA/OpenRA.Platforms.Default/Sdl2GraphicsContext.cs:267
  at OpenRA.Platforms.Default.ThreadedGraphicsContext.RenderThread (object) [0x001ba] in /home/x/source/cs/OpenRA/OpenRA.Platforms.Default/ThreadedGraphicsContext.cs:119
  at System.Threading.ThreadHelper.ThreadStart_Context (object) [0x00036] in <d13c8b563008422a8c5aaec0a74089cc#24B6BFF2-4F08-E2DD-AA7C-9596708ADC74>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00073] in <d13c8b563008422a8c5aaec0a74089cc#24B6BFF2-4F08-E2DD-AA7C-9596708ADC74>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00004] in <d13c8b563008422a8c5aaec0a74089cc#24B6BFF2-4F08-E2DD-AA7C-9596708ADC74>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object) [0x0002f] in <d13c8b563008422a8c5aaec0a74089cc#24B6BFF2-4F08-E2DD-AA7C-9596708ADC74>:0
  at System.Threading.ThreadHelper.ThreadStart (object) [0x0001b] in <d13c8b563008422a8c5aaec0a74089cc#24B6BFF2-4F08-E2DD-AA7C-9596708ADC74>:0
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void__this___object (object,intptr,intptr,intptr) [0x0002e] in <d13c8b563008422a8c5aaec0a74089cc#24B6BFF2-4F08-E2DD-AA7C-9596708ADC74>:0
                                                                                
"<unnamed thread>"                                                              
"Finalizer"    

`
----
perf top output

`                                                                               
  99.33%  SDL2.so   [.] X11_SafetyNetErrHandler                                 
   0.06%  [kernel]  [k] prepare_exit_to_usermode                                
   0.04%  [kernel]  [k] native_write_msr                                        
   0.02%  [kernel]  [k] swapgs_restore_regs_and_return_to_usermode              
   0.02%  [kernel]  [k] interrupt_entry                                         
   0.02%  [kernel]  [k] timekeeping_advance                                     
   0.02%  [kernel]  [k] native_irq_return_iret                                  
   0.01%  [kernel]  [k] __update_load_avg_se                                    
   0.01%  [kernel]  [k] update_load_avg                                         
   0.01%  [kernel]  [k] pvclock_gtod_notify                                     
   0.01%  [kernel]  [k] perf_event_task_tick                                    
   0.01%  [kernel]  [k] trigger_load_balance                                    
   0.01%  [kernel]  [k] _raw_spin_lock_irqsave                                  
   0.01%  [kernel]  [k] __update_load_avg_cfs_rq                                
   0.01%  [kernel]  [k] read_tsc                                                
   0.01%  [kernel]  [k] __hrtimer_run_queues                                    
   0.01%  [kernel]  [k] intel_pstate_update_util                                
   0.01%  [kernel]  [k] __run_timers.part.0                                     
   0.01%  [kernel]  [k] __hrtimer_next_event_base                               
   0.01%  [kernel]  [k] native_read_msr                                         
   0.01%  [kernel]  [k] ktime_get_update_offsets_now                            
`

----
gdb, display original error handler, which points the same function.

`
(gdb) x orig_x11_errhandler
0x7fc96d8ea220 <X11_SafetyNetErrHandler>:       0x415641f789495741
`

----
Possible work around:
- SDL should check to see if orig_x11_errhandler does not equal the current function
- SDL should check if destroy was called from the same thread as init

**Comment by anvilvapre** [comment]
Description:    Ubuntu 20.04.1 LTS
Platform is Linux
Engine version is {DEV_VERSION}
Runtime: Mono 6.12.0.107 (tarball Thu Dec 10 05:26:45 UTC 2020) CLR 4.0.30319.42000
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1600x900
Using resolution: 1024x768
Using window scale 1.00
OpenGL renderer: Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2)
OpenGL version: 4.5 (Core Profile) Mesa 21.0.0-devel (git-05ad0f8 2020-12-19 focal-oibaf-ppa)
Using default sound device
Internal mods:
        modcontent: Mod Content Manager ({DEV_VERSION})
        d2k: Dune 2000 ({DEV_VERSION})
        cnc: Tiberian Dawn ({DEV_VERSION})
        ts: Tiberian Sun ({DEV_VERSION})
        ra: Red Alert ({DEV_VERSION})
        all: All mods ({DEV_VERSION})
External mods:
        ra-{DEV_VERSION}: Red Alert ({DEV_VERSION})
        cnc-27922.git.2c49946: Tiberian Dawn (27922.git.2c49946)
Loading mod: ra

**Comment by pchote** [comment]
Probably fixed by https://hg.libsdl.org/SDL/rev/e0220c4bc306 which is probably included in the new SDL 2.0.14 release (I don't know how to efficiently navigate their mercurial interface so don't know for sure).

**Comment by anvilvapre** [comment]
I downloaded and unzipped 2.0.14. There it seems to still exist, currently.

**Comment by anvilvapre** [comment]
Closing for now. While not seen by others.
