### ISSUE TITLE
Harvesters can get stuck on unloading

### ISSUE THREAD

**Issue by ScottNZ** [OpenRA/OpenRA#3089]
They seem to get stuck at the refinery when multiple harvesters are about to unload at the same refinery. The harvester that should unload does not unload and only unloads after you explicitly order it to. It happens pretty often during games where you have multiple harvesters attached to one refinery.
##

**Comment by x-a-n-a-x** [comment]
It seems the problem has resurrected in the latest bleed: https://github.com/OpenRA/OpenRA/commit/43c3621ef697cbe3158e105eee5efd7a9844aa93
Tomsons26 told me that his harvesters were stuck in front of a Refinery. Chokepoint map.

![weee2pnt_o](https://cloud.githubusercontent.com/assets/1732773/6489799/ae7c9400-c2a1-11e4-83ef-16306bb1fe28.png)

![haviechoke](https://cloud.githubusercontent.com/assets/1732773/6489804/bb6060ca-c2a1-11e4-9fe4-f91f2a179442.png)

**Comment by pchote** [comment]
This indeed appears to be much worse (tending towards unplayable) on latest bleed.  This will be a regression from the recent pathfinder changes.

**Comment by Mailaender** [comment]
See also https://github.com/OpenRA/OpenRA/issues/7610.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/7618 comes with a proposed fix.

**Comment by MicroJOo** [comment]
@Mailaender #7618  is not a fix for this problem ... i allready gave it a test ...

**Comment by Rydra** [comment]
My proposed solution should only solve a crash that may happen on a crowded situation, but does not solve the problem of blocked harvesters.

Can anyone point out which parts of the code deal with those harvester jams?

**Comment by pchote** [comment]
@Rydra: the harvester problem probably originates from a behavioral change in `MobileInfo.CanEnterCell`.  This appears to be the same as the problem (the "obvious bug fix" that broke harvesters) that I mentioned in #7565.  I would double check your changes to that code, and also look at the nudging code that uses it (which is where the real problem probably lives).

**Comment by Rydra** [comment]
Weird because I haven't touched anything relevant on nuding or mobile. I'll check it out and debug what happens.

**Comment by Rydra** [comment]
ok I can see what's going on. I've checkout to a prior commit to my implementation of pathfinder and I can see that harvesters on a crowded (8 harvesters, one refinery, funny name) situation work on a quite weird way 4 harvesters manage each other quite well and work normally but the other remaining stay idle in a resource collection area, because they are never able to find a Path BECAUSE of this code that could be found in legacy Pathfinder:

                        if (customCost != null)
			{
				var c = customCost(p.Location);
				if (c == int.MaxValue)
					return p.Location;
			}

Having said this, I solved it in #7618 to behave exactly in the same way as before. In a crowded situation, harvesters will remain idle and motionless in their harvesting spots until there's a new refinery with 3 or less occupancy.

**Comment by Rydra** [comment]
I wanted to ask... there are a crapload of code parts where int.Maxvalue is being used to represent an invalid value. I have even found some parts where I could operate (sum, multiply, etc...) this maxValue leading to some unexpected overflows and weird values.

Is there any reason about why the code originally was not using nullable types?

**Comment by penev92** [comment]
I didn't see anything like this when testing  #7618, and a few other people confirmed.
Now that that is merged, I'm closing this again.

**Comment by abcdefg30** [comment]
This is still not fixed:
> 22:25:19 (pr37) ore harvesters still block each other.
22:26:28  (abcdefg30) :(
22:26:46  (abcdefg30) but ok, how many do you have per refinery?
22:27:13  (pr37) once there was a block with 3 harvesters, another time with two.
22:27:39  (abcdefg30) that *should* be fixed actually :/
22:32:15  (pr37) abcdefg30, http://www.filedropper.com/openra-2015-04-25t214318z-blocked
22:32:57  (pr37) abcdefg30, at around 5:20 and 7:50, player hotze.
22:35:19  (pr37) map was Regeneration Basin
22:38:21  (abcdefg30) k, saw it, thanks
22:38:36  (pr37) you're welcome
22:38:37 (abcdefg30) guess i need to reopen an issue

**Comment by reaperrr** [comment]
Might have been fixed (or at least improved) in #8622, but this needs more testing.

**Comment by GraionDilach** [comment]
It happens in my mod with the AIs, so this is sadly still existing.

**Comment by reaperrr** [comment]
A possible solution might be to make harvesters nudge away nearby units after they finish unloading.

**Comment by pchote** [comment]
IIRC we do that for production factories, so it seems reasonable to do that for refineries and service depots too.

**Comment by RoosterDragon** [comment]
I have confirmed this is still a problem on the current bleed, none of the other harvester logic changes we've made have accidentally fixed this for us yet.

**Comment by reaperrr** [comment]
Does anyone plan to fix it for this release? If not, I think we should move this to Next+1 or Future.

**Comment by pchote** [comment]
Harvester nudging sounds like a simple fix to implement.  I might give it a shot some time before the release.

**Comment by reaperrr** [comment]
I don't want to scope-creep, but if you're looking at the harvester `UnblockRefinery` code anyway, I'm 100% sure there's some duplication between `Harvester.UnblockRefinery()` and the part of `FindResources` where it's called, but my attempts at getting rid of that always resulted in freezes. Chances are high you would have more luck at not breaking anything.

**Comment by pchote** [comment]
After looking at this more deeply any short term fix for this is going to require a hack to find the cells that need to be nudged clear.  A proper implementation of this would be to define explicit entrance and exit cell sets (which may overlap, but don't need to), which I imagine will come as part of a proper docking implementation.

Unless people thing this is high enough priority to justify a short&rarr;medium&rarr;long term (given our track record) hack, I think this is best left for the future.
