### ISSUE TITLE
Bot still control units/buildings that have been captured

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#8241]
In RA in mission "survive 01" the bot continue to control vehicles that are hijacked.
In TD in mission "Invasion of Egypt (a)" the bot continue to control buildings i have captured.

**Comment by abcdefg30** [comment]
> In RA in mission "survive 01" the bot continue to control vehicles that are hijacked.

Are you sure about that? I tought I fixed that in #8014.

> In TD in mission "Invasion of Egypt (a)" the bot continue to control buildings i have captured.

I filed #8243. I hope that finally fixes those issues.

**Comment by Snurre86** [comment]
Yes the first thing might be fixed, don't know.

**Comment by Snurre86** [comment]
Still happens in playtest_2015-05-24

This is mission "Warthog Hunt"
![openra game_2015_05_28_16_05_39_591](https://cloud.githubusercontent.com/assets/7798635/7862291/3985c72e-0555-11e5-88d6-98d1063faa57.png)

**Comment by abcdefg30** [comment]
The fix was merged only a day ago... so of course this is still in the playtest.
