### ISSUE TITLE
Units with minimum range can't find their way to shoot.

### ISSUE THREAD

**Issue by scshunt** [OpenRA/OpenRA#9789]
Version: release-20150919

Steps to reproduce: Open an RA game, and build an artillery or V2 launcher. Place it directly next to an enemy building and order it to attack.

Expected behaviour: Unit will move away from the building until it is in range, and then attack.

Observed behaviour: Unit will move side to side a bunch but never attack.

**Comment by atlimit8** [comment]
They move away in bleed (the development version) when I tested.
The next release shouldn't have this problem assuming it is not broken in between.

**Comment by scshunt** [comment]
I can still reproduce this on bleed. The V2 launcher goes in circles.

**Comment by atlimit8** [comment]
OK - reopening.

**Comment by RoosterDragon** [comment]
I can also reproduce this on bleed - as well as several versions back.

In really old versions they just sit tight and don't move if the target is too close.

**Comment by pchote** [comment]
> In really old versions they just sit tight and don't move if the target is too close.

I fixed this in #5617, and it seemed to work properly for at least a while after that.

**Comment by RoosterDragon** [comment]
Nope - this reproduces in 3be26e4cda9e5ae82a01a75ba10536a771c72b68 too (with the "loop left and right forever" behaviour).

**Comment by scshunt** [comment]
One possible partial cause is that in `OpenRA.Mods.Common/Activities/Move/MoveWithinRange.cs`, `CandidateMovementCells` should check for `dxSq > innerSq`, not `>=`, but that fix alone does not fix the bug altogether.

**Comment by atlimit8** [comment]
Does anyone have an idea why artillery works but not V2 launcher?

**Comment by GraionDilach** [comment]
V2 has 8 facings for attack but 32 on the body, could that be related?

**Comment by scshunt** [comment]
I was able to get artillery to do it too; I suspect it's highly dependent on conditions. I'll see if I can get a consistent repro.

**Comment by scshunt** [comment]
And now my ability to reproduce it at all appears to have disappeared...

**Comment by atlimit8** [comment]
Great, a heisenbug.

**Comment by RichSuther** [comment]
I find I can reproduce it pretty easily, I'll see if i can track it down.
